name: mini
channels:
  - dglteam
  - pyg
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  # Core ML packages
  - pytorch=1.13.0
  - pytorch-cuda=11.7
  - pyg=2.2.0
  - dgl-cuda11.7
# Core Graph packages
  - ogb=1.3.5
# Tracking
  - neptune-client=0.16.13
# Python tools
  - jupyter=1.0.0
  - matplotlib=3.6.2